# Generated by Django 3.1.3 on 2021-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('des', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('sub', models.CharField(choices=[('maths', 'Maths'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('programming', 'Programming')], max_length=20)),
                ('loc', models.CharField(max_length=100)),
                ('desp', models.TextField()),
            ],
        ),
    ]
