# Generated by Django 3.1.3 on 2021-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='lev',
            field=models.CharField(choices=[('Grade', 'Grade'), ('Secondary', 'Secondary'), ('Intermediate', 'Intermediate'), ('B.Tech', 'B.Tech')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Programming', 'Programming')], max_length=20),
        ),
    ]
