# Generated by Django 3.1.3 on 2021-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0003_auto_20210429_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='exp',
            field=models.IntegerField(default=25, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Lecturer', 'Lecturer'), ('Asst Prof', 'Asst'), ('Assoc Prof', 'Assoc'), ('Prof', 'Prof'), ('Other', 'Other')], max_length=20, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desp',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email id'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='lev',
            field=models.CharField(choices=[('Grade', 'Grade'), ('Secondary', 'Secondary'), ('Intermediate', 'Intermediate'), ('B.Tech', 'B.Tech'), ('Other', 'Other')], max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='loc',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='phno',
            field=models.CharField(max_length=10, verbose_name='Ph.No'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Programming', 'Programming'), ('Other', 'Other')], max_length=20, verbose_name='Subject'),
        ),
    ]
