# Generated by Django 3.1.3 on 2021-04-30 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tfinder', '0004_auto_20210430_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registered By'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='des',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Lecturer', 'Lecturer'), ('Asst Prof', 'Asst Professor'), ('Assoc Prof', 'Assoc Professor '), ('Professor ', 'Professor '), ('Other', 'Other')], max_length=20, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='lev',
            field=models.CharField(choices=[('Grade', 'Grade'), ('Secondary', 'Secondary'), ('Intermediate', 'Intermediate'), ('B.Tech', 'B.Tech'), ('Other', 'Other')], max_length=20, verbose_name='Highest Level'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sub',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Programming', 'Programming'), ('Other', 'Other')], max_length=20, verbose_name='Expect Subject'),
        ),
    ]
