# Generated by Django 3.1.3 on 2021-04-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0006_auto_20210430_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='owner',
        ),
    ]
