# Generated by Django 3.1.3 on 2021-05-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0010_auto_20210501_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='owner',
        ),
    ]
