# Generated by Django 3.1.3 on 2021-05-02 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tfinder', '0014_auto_20210501_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='posted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=10, verbose_name='Ph.No')),
                ('email', models.EmailField(max_length=254, verbose_name='Email id')),
                ('des', models.CharField(max_length=100, verbose_name='Designation')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, verbose_name='Gender')),
                ('sub', models.CharField(max_length=20, verbose_name='Expect Subject')),
                ('lev', models.CharField(max_length=20, verbose_name='Highest Level')),
                ('exp', models.IntegerField(verbose_name='Experience')),
                ('loc', models.CharField(max_length=100, verbose_name='Location')),
                ('desp', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
