# Generated by Django 3.1.3 on 2021-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0015_auto_20210502_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted',
            name='age',
        ),
        migrations.AlterField(
            model_name='posted',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Any', 'Any')], max_length=20, verbose_name='Gender'),
        ),
    ]
