# Generated by Django 3.1.3 on 2021-05-02 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0018_posted_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted',
            name='status',
        ),
        migrations.AddField(
            model_name='posted',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posted',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
