# Generated by Django 3.1.3 on 2021-05-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfinder', '0019_auto_20210502_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted',
            name='expiration_date',
        ),
    ]
